version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Supersecret1
      MONGO_INITDB_DATABASE: openf1
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - f1_network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo_db_ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Supersecret1
      ME_CONFIG_MONGODB_URL: mongodb://admin:Supersecret1@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - f1_network

volumes:
  mongodb_data:

networks:
  f1_network:
    driver: bridge